spring:
  datasource:
    dynamic:
      # HiKari连接池在springboot2.0上默认使用无需配置
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          username: root
          password: Admin123!
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.11.241:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowMultiQueries=true&serverTimezone=GMT%2b8
# Redis数据源
  redis:
    host: 172.16.11.241
    port: 6379
    timeout: 6000
    password: Admin123!
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

jwt:
  # 需要认证的url，多个URL使用英文逗号,分割
  authorised-urls: /api/**
  # tocken 过期时间，单位秒
  expire: 300
  # 加密yan
  secret: A0B1C2D3E4F5G6H7I8J9KALBMCNDOEPFQ0R1S2T3U4V5W6X7Y8Z9